version: "2"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:10-debian-10
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: 
      docker.io/bitnami/redis:6.0-debian-10
    volumes: 
      - redis_data:/bitnami
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2-debian-10
    environment: 
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW**CORE**LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW**WEBSERVER**DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW**CORE**DEFAULT_TIMEZONE=Asia/Seoul
    volumes: 
      - ./dags:/opt/bitnami/airflow/dags
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2-debian-10
    environment: 
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW**CORE**LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW**WEBSERVER**DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW**CORE**DEFAULT_TIMEZONE=Asia/Seoul
    volumes: 
      - ./dags:/opt/bitnami/airflow/dags
  airflow:
    image: docker.io/bitnami/airflow:2-debian-10
    environment: 
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW**CORE**LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW**WEBSERVER**DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW**CORE**DEFAULT_TIMEZONE=Asia/Seoul
    ports:
      - 8080:8888
    volumes:
      - ./dags:/opt/bitnami/airflow/dags

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
